---
# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build-and-test:
    docker:
      - image: circleci/golang:1.11
    working_directory: /go/src/github.com/p2pderivatives/dlc
    steps:
      - run:
          name: add-localbin
          command: echo "export PATH=$(pwd)/.bin:$PATH" >> $BASH_ENV
      - checkout
      - run:
          name: install-go-packages
          command: |
            dep ensure
      - restore_cache:
          keys:
            - bitcion-cache-{{ checksum "./.circleci/install_bitcoin.sh" }}
      - run:
          name: install-bitcoin
          command: ./.circleci/install_bitcoin.sh
      - save_cache:
          key: bitcion-cache-{{ checksum "./.circleci/install_bitcoin.sh" }}
          paths:
            - ./.bin/bitcoind
            - ./.bin/bitcoin-cli
      - run:
          name: run-bitcoind
          command: make run_bitcoind
          background: true
      - run:
          name: build
          command: go build -v ./...
      - run:
          name: test
          command: go test -count=1 -v ./...
      - run:
          name: stop-bitcoind
          command: make stop_bitcoind
  lint:
    docker:
      - image: circleci/golang:1.11
    working_directory: /go/src/github.com/p2pderivatives/dlc
    steps:
      - checkout
      - run:
          name: install-go-packages
          command: |
            dep ensure
      - run:
          name: linter-installation
          command: |
            go get -v github.com/alecthomas/gometalinter
            gometalinter --install
            go get -u github.com/bradleyfalzon/revgrep/...
      - run:
          name: linter
          command: |
            set +o pipefail
            gometalinter ./... |& revgrep origin/master

workflows:
  version: 2
  build-test-lint:
    jobs:
      - build-and-test
      - lint
